version: 2
updates:
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: pub
    groups:
      dart-ecosystem:
        patterns:
          - "web3dart"
          - "eth_sig_util"
          - "convert"
          - "http"
          - "crypto"
          - "pointycastle"
      dev-dependencies:
        patterns:
          - "lints"
          - "test"
          - "melos"
          - "build_runner"
          - "mockito"
          - "coverage"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ci
