name: Publish permissionless

on:
  push:
    tags:
      - 'permissionless-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write  # required for OIDC trusted publishing
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      environment: release
      working-directory: packages/permissionless
